### ISSUE TITLE
Washing Machines can be rendered inoperable by pulling dirty clothes out without washing

### ISSUE THREAD

**Issue by PvtStupidhead** [sojourn-13/sojourn-station#3907]
As the title describes, right now there's a glitch that makes it so you cannot use the washing machine after pulling a dirty item out of it (e.g. not using the wash function). Here is how to replicate the glitch:

First, get 2 pieces of dirty laundry.

Second. Put in one of the dirty laundry and clean it.

Third. Put in the 2nd piece of dirty laundry, but instead of activating the washing machine, pull out the dirty clothing.

Four. Try to put it back in. Congratulations, you cannot do this right now.

This is a rather disruptive and easily performed glitch to those who use the Washing Machines frequently, so please try and get it fixed quickly.

With love, Stupidhead.

**Comment by du-top** [comment]
I'm unable to reproduce your issue. Please help me to find where I do things differently than you.

| Description      | Your step | State of machine |
| ---------------- | --------- | ---------------- |
| Standard         | 1         | E_OD             |
| put laundry in   | 2.1       | F_OD             |
| close door       | 2.2       | F_CD             |
| start washing    | 2.3       | RUN              |
| washing finished | 2.4       | F_CD             |
| remove laundry   | 3.1       | E_OD             |
| put laundry in   | 3.2       | F_OD             |
| close door       | 3.3       | F_CD             |
| open door        | 3.4       | E_OD             |
| put laundry in   | 4         | F_OD             |
 
I've shortened the state, because if I have to see WASHSTATE_EMPTYOPENDOOR and similar more often, my brain will melt:
E_XX: Empty
F_XX: Full
X_OD: Open door
X_CD: Closed door
RUN: Running

I can repeat that, but I just don't get the same issue as you.

BUT! If you click with an empty hand on the washing machine while it's empty and the door is open, you close the door. The icon of the washing machine does not change! (Well, it does, but the icon for E_OD (wm_1) is the same as for E_CD (wm_2)). When you try to put laundry in, you'll get "You can't put the item in right now". Sounds like your issue, but the process to get it is not what you described. In that case, you click the washing machine again with an empty hand, the door opens (still no icon change) and you can put laundry in.

![image](https://user-images.githubusercontent.com/73559117/205444668-50a828a9-45f4-48e9-8d64-8516bc397345.png)


Please tell me if I did something different than you and if clicking the machine helps.

**Comment by du-top** [comment]
If that's your issue, I'll make an PR with this:
![image](https://user-images.githubusercontent.com/73559117/205449099-a54d13f3-4abc-4e1e-91da-d62a08ee6fcb.png)

**Comment by PvtStupidhead** [comment]
> I'm unable to reproduce your issue. Please help me to find where I do things differently than you.
> 
> Description	Your step	State of machine
> Standard	1	E_OD
> put laundry in	2.1	F_OD
> close door	2.2	F_CD
> start washing	2.3	RUN
> washing finished	2.4	F_CD
> remove laundry	3.1	E_OD
> put laundry in	3.2	F_OD
> close door	3.3	F_CD
> open door	3.4	E_OD
> put laundry in	4	F_OD
> I've shortened the state, because if I have to see WASHSTATE_EMPTYOPENDOOR and similar more often, my brain will melt: E_XX: Empty F_XX: Full X_OD: Open door X_CD: Closed door RUN: Running
> 
> I can repeat that, but I just don't get the same issue as you.
> 
> BUT! If you click with an empty hand on the washing machine while it's empty and the door is open, you close the door. The icon of the washing machine does not change! (Well, it does, but the icon for E_OD (wm_1) is the same as for E_CD (wm_2)). When you try to put laundry in, you'll get "You can't put the item in right now". Sounds like your issue, but the process to get it is not what you described. In that case, you click the washing machine again with an empty hand, the door opens (still no icon change) and you can put laundry in.
> 
> ![image](https://user-images.githubusercontent.com/73559117/205444668-50a828a9-45f4-48e9-8d64-8516bc397345.png)
> 
> Please tell me if I did something different than you and if clicking the machine helps.

Hello, sorry for the delay.

If we're going by the steps you did, it'd be akin to this:
| Description  |Step | State of machine/Consequence|
| ------------- | ------------- | ------------- |
| Put laundry inside| 1 | E_OD>F_OD|
| Close the washing machine  | 2 | F_OD>F_CD  |
| Run washing machine  | 3| F_CD>RUN |
| Wait for washing machine to finish | 4 | RUN>F_CD|
| Pull empty clothes out of machine | 5  | F_CD>E_OD  |
| Insert new batch of dirty clothes | 6 | E_OD>F_CD|
| PULL OUT the newly added dirty clothes without running cycle | 7 | F_CD>E_OD |
| Attempt inserting in the previous dirty clothes from step 7 or new ones  | 8 | E_OD>(?) |

A fix that I noticed last time was that if you used an empty hand on the open-empty washing machine you can then re-insert clothing, exactly as what you described in your reply.

Your suggestion to fix the wm_2 to properly reflect that it's a closed door sounds good for me.

Thank you for taking your time to reply to this issue with a possible fix!
