### ISSUE TITLE
Infinite puking glitch

### ISSUE THREAD

**Issue by OhgodwhyIhavetosingupforeverything** [sojourn-13/sojourn-station#4254]
If you fix a infection with antibiotics but don't fix the infected wound it reaches a point where a character will puke non stop no matter what you do to fix it.

**Comment by ThePainkiller** [comment]
Can you specify what you mean with "fix the infected wound"? This sounds like necrosis was present on the person and they just gave them spaceacillin instead of treating the issue through surgery. How much interval is there between pukes? (this is important as it'd really be a bug rather than just puking often because of high infection / massive toxins)

**Comment by Trilbyspaceclone** [comment]
No longer an issue that has been reported likely randomly fixed in a random pr
