### ISSUE TITLE
Pepperball rounds don't seem to to work.

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4667]
As stated tested on a monkey. Tried shotgun and 10mm pepperballs and found no Condensed Capsaicin or unknown chems in their system on a health scanner and no visible signs of Capsaicin (coughing etc). Including a headshot on the off chance it was meant to work that way.

**Comment by du-top** [comment]
_Should_ there be chemicals in their system? To me, it doesn't seem that it's supposed to work this way. That's not how pepperspray works, either, for comparison. Using that on a mob sets variables like stunned, eye_blind and eye_blurry on a value greater than zero. stunned - you're on the floor. eye_blind - you only see a small circle around your char, rest is black. eye_blurry - everything's foggy. stunned gets a small value, eye_blurry a big one. These values tick down and their effect stops when their value gets to 0.
On the other hand, injecting capsaicin didn't have much effect.
So, I've shot pun pun with the Grizzly, loaded with /obj/item/ammo_casing/shotgun/beanbag/pepperball. Shot Pun Pun, he was stunned, blinded and blurried.
But you said 10mm pepperballs. That would be the /obj/item/ammo_casing/magnum_40/rubber/pepperball, I think. No idea what shotgun is able to take em.

**Comment by benj8560** [comment]
I'm far from a coder but a short look at the code and it really seems to suggest its suppose to transfer Condensed Capsaicin. Injecting Condensed Capsaicin? Not sure what effect that has. Its placed in the stomach when sprayed or breathed. 

The code making me feel its suppose to found under  /obj/item/projectile/bullet/magnum_40/rubber/pepperball

var/spray = "condensedcapsaicin"

/obj/item/projectile/bullet/magnum_40/rubber/pepperball/New()
	..()
	if (!testing)
		create_reagents(5)
		reagents.add_reagent(spray, 5)
		
		
These are just small snips of the code but they function exactly as soporific bullets as far as I can tell.

**Comment by du-top** [comment]
The code snippet you showed shows how the bullet is filled with reagents, not the target. That happens in the on_hit method right below. Or should happen?
Thanks for the nudge towards soporific bullets. They work different. So where's the difference?
/obj/item/projectile/bullet/magnum_40/rubber/pepperball/on_hit uses
`reagents.trans_to_mob(L, 5, CHEM_TOUCH, copy = FALSE)`

/obj/item/projectile/bullet/pistol_35/rubber/soporific/cbo/on_hit (yeah, pistol_35, couldn't find any usage of magnum_40 in-game) uses
`L.reagents.add_reagent("stoxin", 5)`

So, the compressed soporific bullet enters the bloodstream. The pepperball should hit the target and add the reagents to the touched variable. Funnily that worked exactly one time, when I changed the wrong thing and therefore, by accident, tested the normal, unchanged pepperball bullet type.

For testing purposes, I used the L.reagents.add_reagent approach for the pepperball and it worked. The capsipapsicapsi went into the bloodstream. Where it doesn't to anything (see my comment above). So that won't help.

So I looked at the trans_to_mob approach. I see nothing wrong in /datum/reagents/proc/trans_to_mob or /datum/reagents/proc/trans_to_holder. I guess it worked when these pepperballs were added in #4491.

**Comment by cdb-is-not-good** [comment]
Brief testing indicates pepperball is still functional. On this code pepperspray works a little weird, enacting its effects by being ingested rather than by checking eye/face covering and applying effects based on how unprotected you are.

**Comment by cdb-is-not-good** [comment]
Closing for now, if someone can reproduce the apparent issue please poke me and I'll reopen this.
