### ISSUE TITLE
Weapon overclocking.

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4740]
So many of the guild weapons allow for the  safety bolts to be undone to fire their fancy fire modes.  Saaadly this no longer works. It's only a guess but I'm assuming it's related to the recent PR preventing energy weapons from being broken down. Pretty sure that was a thing that happened.

To be clear the part that's not working is wrenching the weapons to disable the safety

**Comment by cdb-is-not-good** [comment]
Please list exactly which weapons aren't working.

**Comment by benj8560** [comment]
all of them as far as I'm aware.

**Comment by benj8560** [comment]
maybe your asking for exact names. Whatever weapons that share the same parent as the rail rifle/pistol/bat'ko etc

**Comment by cdb-is-not-good** [comment]
> maybe your asking for exact names. Whatever weapons that share the same parent as the rail rifle/pistol/bat'ko etc
> 
> edit: every child of this /obj/item/gun/energy/laser/railgun

None of the weapons that are children of that path mention having safeties that are able to be turned off with a wrench. Are you sure you're not thinking of the shellshock?

**Comment by benj8560** [comment]
> None of the weapons that are children of that path mention having safeties that are able to be turned off with a wrench. Are you sure you're not thinking of the shellshock?

The rail pistol/rifle, shellshock, abdicator, Bat'ko. Might be more? You will notice all these weapons have on their last fire setting some kind of explosive setting that exceeds the max capacity of the largest power cells available. Disabling the safety allows you to fire these at the cost of destroying the cells. They all allowed this before I assure you.

**Comment by cdb-is-not-good** [comment]
So do these fire modes not work anymore at all?

**Comment by benj8560** [comment]
no since again they are intended to be used with the safety disabled

**Comment by cdb-is-not-good** [comment]
It seems we're both mistkaen. The reductor is still working with the safety disabling - because it HAS code to disable the safeties, which the others lack? I'm assuming at some point the pistol/Bat'ko were a child of the reductor. The abdicator also lacks the code - why? because some fool gave it this grenade launching feature that I originally had not coded it to include and failed to actually add the code for it....despite it ALSO not being a child of the reductor. 
![image](https://github.com/sojourn-13/sojourn-station/assets/87905328/dedb9fd4-f3c2-4b7e-bdad-d72597554795)
