### ISSUE TITLE
Bleeding while dead.

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4767]
So with are tweaks to bleeding making it far more lethal as you pass below 40% 0% blood cases have become....very bad not impossible to fix but a pain in the butt regardless.

Only two ways I've seen to manage this first way is NSA. One of the extreme NSA effects make you bleed even while dead you will even carry on pooling blood onto the floor after you've run out. 

Second way is being cocoons slowly drain you of blood they already kill you near instantly. This one is at least slightly less of a issue it takes ages to fully drain someone and more then enough time for someone to recover you provided someone is around to do so.

**Comment by cdb-is-not-good** [comment]
seems to work with this latest bugfix but I'm also not 100% sure you guys are actually correct about people bleeding *after death*. high NSA seems to be implicated in the issue but I have so far seen zero evidence that people are bleeding after dying - maybe it's from people just lying in critical for extended periods with their NSA sky high rather than dying right away? Unsure, either way we added a check to stop the NSA bleed effect after you run down to a certain level of bloodloss

**Comment by benj8560** [comment]
I can't keep someone alive with under 15% blood for more then a few seconds with a fully stocked medbay. It is IMPOSSABLE for someone to reach 0% blood and be alive as we are now.  If it's fixed great but I've 0 doubt in my mind that lethal NSA was allowing for bleeding after death
